name: Bug Report
description: Something isn't working
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: What happened?
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: What did you expect?
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
  - type: input
    id: os
    attributes:
      label: Operating system
      placeholder: "Windows 11 / macOS 15 / Ubuntu 24"
